-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

-- ── Autostart ──



-- ── Environnement ──

hl.env("PATH", "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin")

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", 24)

hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

-- ── Entrée ──

hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = true,
        },
    },
})

-- ── Général ──

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 1,
        layout = "dwindle",
        col = {
            active_border = "rgba(c8b89aee)",
            inactive_border = "rgba(1a1814aa)",
        },
    },
})

-- ── Décoration ──

hl.config({
    decoration = {
        rounding = 0,
        blur = {
            enabled = false,
        },
        shadow = {
            enabled = false,
        },
    },
})

-- ── Animations ──

hl.config({
    animations = {
        enabled = true,
    },
})

-- ── Layout dwindle ──

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

-- ── Layout master ──

hl.config({
    master = {
        new_status = "master",
        mfact = 0.55,
    },
})

-- ── Règles fenêtres Quickshell ──

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(quickshell)$",
    },
    float = true,
})

hl.window_rule({
    name  = "pin_on",
    match = {
        class = "^(quickshell)$",
    },
    pin = true,
})

hl.window_rule({
    name  = "no_blur_on",
    match = {
        class = "^(quickshell)$",
    },
    no_blur = true,
})

hl.window_rule({
    name  = "no_shadow_on",
    match = {
        class = "^(quickshell)$",
    },
      no_shadow = true,
})

hl.window_rule({
    name  = "workspace_special_sp",
    match = {
        class = "^(Spotify)$",
    },
    workspace = "special:spotify",
})

hl.window_rule({
    name  = "fullscreen_on",
    match = {
        class = "^(Spotify)$",
    },
    fullscreen = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(qs-yazi-picker)$",
    },
        float = true,
})

hl.window_rule({
    name  = "size_900_600",
    match = {
        class = "^(qs-yazi-picker)$",
    },
    size = "900 600",
})

hl.window_rule({
    name  = "center_1",
    match = {
        class = "^(qs-yazi-picker)$",
    },
    center = 1,
})

-- ══════════════════════════════════════════════════

-- RACCOURCIS

-- ══════════════════════════════════════════════════

-- ── Launcher (menu applications) ──

hl.bind("SUPER" .. " + " .. "Super_L", hl.dsp.exec_cmd("echo t >>/tmp/qs-menu"), { repeating = true })

-- SUPER + SUPER → ouvre/ferme le menu (pour éviter les conflits avec d'autres raccourcis utilisant SUPER)

hl.bind("SUPER" .. " + " .. "Tab", hl.dsp.exec_cmd("~/.config/quickshell/ctrl.sh"))

-- ── Lockscreen Quickshell ──

hl.bind("SUPER" .. " + " .. "L", hl.dsp.exec_cmd("~/.config/quickshell/lock.sh"), { repeating = true })

-- ── Player Quickshell ──

hl.bind("SUPER" .. " + " .. "Return", hl.dsp.exec_cmd("echo t >>/tmp/qs-toggle"))

hl.bind("SUPER + SHIFT" .. " + " .. "Return", hl.dsp.exec_cmd("echo t >>/tmp/qs-front"))

-- ── Applications ──

hl.bind("SUPER" .. " + " .. "T", hl.dsp.exec_cmd("/usr/bin/kitty"))

hl.bind("SUPER" .. " + " .. "M", hl.dsp.exec_cmd("pgrep -x spotify >/dev/null && hyprctl dispatch togglespecialworkspace spotify || spotify"))

hl.bind("SUPER" .. " + " .. "R", hl.dsp.exec_cmd("pkill qs"))

hl.bind("SUPER" .. " + " .. "P", hl.dsp.exec_cmd("~/.config/quickshell/wallpaper.sh"))

-- ── Gestion des fenêtres ──

hl.bind("SUPER" .. " + " .. "Q", hl.dsp.window.close())

hl.bind("SUPER" .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind("SUPER" .. " + " .. "V", hl.dsp.window.float())

hl.bind("SUPER" .. " + " .. "Escape", hl.dsp.exit())

hl.bind("SUPER" .. " + " .. "D", hl.dsp.window.fullscreen())

hl.bind("SUPER" .. " + " .. "W", hl.dsp.exec_cmd("hyprctl keyword general:layout master"))

hl.bind("SUPER + SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("hyprctl keyword general:layout dwindle"))

-- ── Focus ──

hl.bind("ALT" .. " + " .. "Tab", hl.dsp.window.cycle_next())

hl.bind("ALT + SHIFT" .. " + " .. "Tab", hl.dsp.window.cycle_next({ next = false }))

-- ── Focus directionnel ──

hl.bind("SUPER" .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind("SUPER" .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind("SUPER" .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind("SUPER" .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- ── Déplacement de fenêtre ──
hl.bind("SUPER + SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "d"}))

-- ── Special workspace ──

hl.bind("SUPER + SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind("SUPER" .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

-- ── Workspaces — ALT + AZERTY ──

hl.bind("ALT" .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind("ALT" .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind("ALT" .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind("ALT" .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind("ALT" .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind("ALT" .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind("ALT" .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind("ALT" .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind("ALT" .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind("ALT" .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- ── Déplacer vers workspace ──

hl.bind("SUPER + SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind("SUPER + SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind("SUPER + SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind("SUPER + SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind("SUPER + SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind("SUPER + SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind("SUPER + SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind("SUPER + SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind("SUPER + SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind("SUPER + SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- ── Scroll workspaces ──

hl.bind("SUPER" .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind("SUPER" .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- ── Souris ──

hl.bind("SUPER" .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind("SUPER" .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- ── Audio ──

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))

-- ── Luminosité ──

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))

-- ── Capture d'écran ──

hl.bind("ALT + SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -m region"))

hl.bind("Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" ~/Screenshots/$(date +%Y%m%d_%H%M%S).png"))

-- ═══════════════════════════════════════════════════════════════════

-- User overrides — see user.conf

-- This file is created empty by the installer and is NEVER overwritten

-- by future updates. Put your monitor setup, custom binds, env vars,

-- theme tweaks, etc. there.

-- ═══════════════════════════════════════════════════════════════════

 local user = require("user")

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("env QT_MEDIA_BACKEND=ffmpeg qs")
    hl.exec_cmd("pkill dunst")
    hl.exec_cmd("pkill mako")
    hl.exec_cmd("pkill swaync")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("~/.config/quickshell/lock.sh")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("/usr/bin/waybar")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("~/.config/quickshell/wave-check.sh")
end)
