-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ═══════════════════════════════════════════════════════════════════

-- Personal Hyprland overrides

-- This file is created empty by the installer and is NEVER overwritten

-- by future updates. Put your monitor configs, custom binds, env vars,

-- theme tweaks, etc. here.

--

-- Examples:

--   monitor = DP-1, 2560x1440@144, 0x0, 1

--   bind    = SUPER, B, exec, firefox

--   env     = GTK_THEME, Adwaita-dark

-- ═══════════════════════════════════════════════════════════════════

hl.bind("SUPER" .. " + " .. "B", hl.dsp.exec_cmd("firefox"))

hl.bind("SUPER" .. " + " .. "E", hl.dsp.exec_cmd("dolphin"))

hl.bind("SUPER" .. " + " .. "K", hl.dsp.exec_cmd("Krita"))

hl.bind("SUPER + SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" -|wl-copy"))

hl.bind("SUPER" .. " + " .. "C", hl.dsp.exec_cmd("coolercontrol"))
